### ISSUE TITLE
Dont work in R6

### ISSUE THREAD

**Issue by VeryHotOrange** [cafali/SnapKey#11]
Dont work right in Rainbow Six Siege. Can u make it work for R6?

**Comment by Potenza52** [comment]
CoD Mw3, XDefiant as well. I was able to get it work just in SP games so I believe they got covered such a "script" in any case thank you for your hard work presentation of SnapKey is brilliant keep up the good work mate.

**Comment by techsrus** [comment]
Tried in Apex, CS 1.6 and it doesn't work. It shows it working in an online keyboard tester, just not in any games. Windows 10.

**Comment by cafali** [comment]
SnapKey adds global systemwide null binds and is not designed to engage with or manipulate any game files.

It is not designed to work with a "specific" game.

For it to work with R6 (or any other game where the input detection is designed this way), you would need to rewrite the code and interact directly with the game files or even the game engine.

There is no need to mention that this could get you banned, as you would be manipulating the game files.
