### ISSUE TITLE
Failure to Open

### ISSUE THREAD

**Issue by tobsmeks** [cafali/SnapKey#16]
When I try to open the program I get error message "Failed to restore config from backup" followed by "SnapKey is already running"

**Comment by cafali** [comment]
Please ensure you unzip all the SnapKey files into a single folder. This includes the meta folder and the default configuration file located in the main directory.

For further assistance, please refer to the SnapKey Wiki Setup Guide:

[SnapKey Setup Guide](https://github.com/cafali/SnapKey/wiki/Setup)
