### ISSUE TITLE
Changeable keybinds?

### ISSUE THREAD

**Issue by TheAmpPlayer** [cafali/SnapKey#2]
I have a problem where I have an EU keyboard, and I was wondering if I could somehow change keybinds?

Instead of the US version where they use A/D I would like to change keybinds to Q/D as example.

**Comment by xXDeathAbyssXx** [comment]
It will be ready when I push in about 8 hours since it is late for me. (#1)

**Comment by TheAmpPlayer** [comment]
Ah I see, seems like there already was a request.

My apologies.

**Comment by xXDeathAbyssXx** [comment]
> Ah I see, seems like there already was a request.
> 
> My apologies.

I don't mean that I already made the PR of your suggestion.

**Comment by cafali** [comment]
Keybinding is now available!

1.1.3 - 07/2024 (latest)

Key Bindings:
Introducing customizable key bindings to accommodate various keyboard layouts such as AZERTY (where A=Q, D=D). You can now modify the keys managed by SnapKey by editing the config.cfg file using the ASCII Code List.

Others:
Updated Readme.pdf
