### ISSUE TITLE
cant find the exe flie

### ISSUE THREAD

**Issue by f3nt1** [cafali/SnapKey#28]
I'm new to GitHub so sorry if I'm slow at this but i downloaded the file and extracted it using 7zip and i cant seem to find the exe file ,am I doing something wrong?

![helpme](https://github.com/user-attachments/assets/84637e4f-0017-40c9-8931-677894fbf0f1)

**Comment by cafali** [comment]
Hi,

download SnapKey from the Release Page: https://github.com/cafali/SnapKey/releases
