### ISSUE TITLE
Linux Support? .appimage?

### ISSUE THREAD

**Issue by Dillacorn** [cafali/SnapKey#4]
As the title requests. Can an .appimage be compiled to operate under a Linux environment?

I'll be understanding if this doesn't work on a Wayland session such as (Sway). 

Maybe the application could work on i3 (X11/Xorg Session) ?

**Comment by cafali** [comment]
The code is specifically designed for Windows, utilizing the Windows API to manage keyboard input and system tray interactions. Consequently, it will not run on Linux systems without modifications.

Currently, I am not looking to convert or rewrite the code for Linux, as there are additional features planned for the future. Additionally, my knowledge of Linux software development is limited. ...sorry

**Comment by Dillacorn** [comment]
No problem! I hope a Linux solution eventually comes along.

**Comment by Dillacorn** [comment]
@cafali Got this working on Linux with Proton! :100: 

Using Flatpak Steam + Flatpak steamtinkerlaunch

Step 1:
Place config.cfg and SnapKey.exe in a folder under Steam game directory.

example directory:
/home/dillacorn/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/compatdata/2365810/pfx/drive_c/Program Files/SnapKey

Step 2:
Launch game with steamtinkerlaunch -> hit spacebar when tinker launcher opens.

Step 3:
Check "Use custom command" and "Fork custom command"

Step 4:
Add SnapKey.exe Application under game directory
example:
/home/dillon/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/compatdata/2365810/pfx/drive_c/Program Files/SnapKey_socd/SnapKey.exe

SAVE AND PLAY

Enjoy :)

Note:
If you click "SAVE" in some cases custom command application looks like it doesn't stick.. It could be a bug with flatpak version not sure? - If this does happen click "SAVE AND PLAY" anyway and an application loader should pop up.. navigate to the directory again and pick the SnapKey.exe again and next time you start the game with steamtinkerlauncher in Steam it should work.

I pretty much primarily game with Proton so I'd say mark this issue as solved! :)

Extra Rant:
I spent at least a week so far troubleshooting and trying to get Snap Key to work on my Gamakay TK68HE.. I just want to thank you dev for writing an awesome program that doesn't use AutoHotkey! :)

I did find an AutoHotkey solution that DID work.. but I'd suggest others to avoid that solution if you can..ESPECIALLY for competitive games that use anti-cheat!

**Comment by cafali** [comment]
That's fantastic news! I'm really glad to hear it's working smoothly for you on Linux with Proton. 
I hope your detailed steps make it clear for anyone else trying to set it up!

Enjoy using SnapKey, and thanks a ton for the appreciation! It means a lot!

**Comment by Dillacorn** [comment]
Edited directions per new findings.

Yes I hope this helps others especially!

It's not the cleanest or even that easy to setup AND tinkerlaunch is kind of buggy occasionally, although it may be due to my **Wayland (Sway)** session.

I've actually had to do a system restart (`sudo reboot now`) because tinkerlaunch wouldn't LAUNCH after configuration so this solution isn't perfect to configure but it does work when launching the game 99% of the time after configuration so that's good..

Next hurdle is creating a copy and replace files in each directory script for when you push a new update.. because I have to have duplicates of the applications in the game directory which is very strange but HAS to be done in order for SnapKey to work along with steamtinkerlaunch. ~ This isn't going to be hard to achieve.

Here is image of an example directory
![2024-07-26T10:34:09,478723694-04:00](https://github.com/user-attachments/assets/f99647d3-327a-446a-80e8-d14c84319743)

**Comment by Tom-jm03** [comment]
Would this also work w/o the flatpak steam version?

**Comment by dillacorn** [comment]
@Tom-jm03 

> Would this also work w/o the flatpak steam version?

Flatpak steamtinkerlaunch is not compatible with non-flatpaked Steam...

You will need to install [steam tinker launch](https://github.com/sonic2kk/steamtinkerlaunch) from your repo provider or through github for your specific distro.

The directories navigation will be slightly different.. If you're using non-flatpak Steam, Steam already has access to your entire file system so place SnapKey.exe + its configuration files in the directory of your choice and follow the rest of the directions from the post for adding SnapKey.exe as a custom command.

Reason I'm using flatpak versions is primarily high compatability and I've personally found there to be no downsides... Unless if you're using an Nvidia GPU which just came to mind..

I want to add I've concluded from using Linux for a long time that flatpak steam is perfectly fine as it packages the latest mesa drivers and through extensive testing has been more flexible in use with every DE and WM that I've tested and used.

"ever DE and WM that I've tested and used" includes GNOME, KDE 5/6, XFCE, DWM Flexipatch, i3 and Sway.

Let me know if you have any more questions I should be able to help.

**Comment by Kyr4l** [comment]
> Uncheck "Use Steam Linux Runtime with Custom Command"

does this setting even exist ? i can only find `USESLR="1"` which doesn't specifically affect the game process

**Comment by Kyr4l** [comment]
the `SnapKey.exe` process doesn't kill itself once the main process dies, meaning that it has to be killed manually after each session, otherwise steam will display a RUNNING status…
does anyone knows a way to kill the `SnapKey.exe` process once a game is stopped ?

**Comment by dillacorn** [comment]
> the `SnapKey.exe` process doesn't kill itself once the main process dies, meaning that it has to be killed manually after each session, otherwise steam will display a RUNNING status…
> does anyone knows a way to kill the `SnapKey.exe` process once a game is stopped ?

If you click "STOP" in Steam it should close the game and any process related to it. I have noticed this behavior but I don't know a solution.. It's not that big of a deal as long as you know you need to also STOP the game within Steam Client as well..
