### ISSUE TITLE
Releases seem to be built in debug mode

### ISSUE THREAD

**Issue by zeozeozeo** [cafali/SnapKey#41]
The latest release (https://github.com/cafali/SnapKey/releases/tag/v1.1.8 at the time of writing) seems to be built in Debug mode instead of Release.

The `SnapKey.exe` file in the release zip is about 3MB in size, while a version that I built locally in Release mode is about 300KB (and about 200KB in RelWithDebInfo, nowhere close to 3MB).

**Comment by cafali** [comment]
Seems about right to me. The executable is compiled with MSYS2 MINGW64 using static libraries without the -g argument, resulting in a file size of around 2.92 MB. When I compile it dynamically, the size is approximately 200 KB.
