### ISSUE TITLE
Mary goes round - Battlefield 4 mouse spins out

### ISSUE THREAD

**Issue by sKGu8gxV** [cafali/SnapKey#50]
Hi,
First, thanks, this looks excellent. However I have an issue. I tried playing Battlefield 4 and the mouse spins out, so like ~50x 360 turns of the camera in a couple of seconds. I tried it in Amid Evil and there it was fine. 

I use Ps/2 usb converter with a Leopold 75% keyboard and W10 19045.2075.

**Comment by cafali** [comment]
There are no functions or hooks in the code that handle mouse events or manipulate mouse input.
BF4 is running on the Frostbite engine. So far, I have not performed any tests on games running on Frostbite.
Not sure about the PS2 adapter... thank God you didn’t mention anything about a ball-mouse.

Please try to download the newest version of SnapKey 1.2.0. This version tweaks input handling (scancode) and adds compatibility with many games made on custom or in-house engines.
