### ISSUE TITLE
Occasional 'Stuck key' in CS2

### ISSUE THREAD

**Issue by NCOOP03** [cafali/SnapKey#61]
Occasionally, when using Snapkey in CS2, a key will 'stick' and stay depressed when it is physically not being pressed in that instance of time. 

Here's what I know. 
-From my experience, it appears that a key may stick when using the inputs (SHFT+A), and in one instance where it was (SHFT+A,S). Occurs when I walk backward in CS. 
-Unsticking the key is done by releasing all keys and selecting the opposite key, and snapkey is back to normal. 

I will attempt to replicate it and report back.

**Comment by dpyrozhok** [comment]
I can confirm that I face following behaviour a lot through out game sessions

**Comment by arthurcgc** [comment]
> I can confirm that I face following behaviour a lot through out game sessions (cs2) and my "Crouch" bind to the SHIFT

Hey @dpyrozhok, they already fixed it in the latest version. Just download the newest release :)

**Comment by happychristian777** [comment]
not working with valorant

**Comment by minteeaa** [comment]
> not working with valorant
few more details would be preferred and helpful, aka
- snapkey version
- snapkey config
- key combinations that cause the issue
- any way to replicate the issue

and if you can consistently replicate the issue, perhaps create a new issue post related
