### ISSUE TITLE
RIP SNAP TAP - not working with cs2

### ISSUE THREAD

**Issue by siwy44** [cafali/SnapKey#67]
I was playing a game like an hour ago, and go instantly kicked after 30 seconds of using it with the message saying "invalid input" or something like that. Cant remember exactly. I had to turn if off so the game wouldn't kick me from the game. Counter Strike 2/CS2

**Comment by CASOTAAA** [comment]
It's been banned by Valve.

https://store.steampowered.com/news/app/730/view/6500469346429581891

**Comment by minteeaa** [comment]
unfortunate. nothing we can do about that, RIP SnapTap on CS2 I suppose

**Comment by herovaxy** [comment]
Thank you minteeaa and cafali for the SnapKey while it's lasts.

**Comment by cafali** [comment]
If Valve could detect rage hackers at this rate, the game would be beautiful... Anyway, I am glad that we saved a lot of people from wasting money on that feature.

**Comment by pidjan** [comment]
add 1 millisecond delay before sendinput in sendkey:
 std::this_thread::sleep_for(std::chrono::milliseconds(1));
SendInput(1, &input, sizeof(INPUT));

**Comment by cafali** [comment]
> @siwy44 @cafali add 1 millisecond delay before sendinput in sendkey, fixes everything:

To clarify, I am not contesting this decision.

As mentioned [here](https://github.com/cafali/SnapKey/wiki/Troubleshoot#p1-snapkey-not-working-in-specific-games): "SnapKey was not created to work with a specific game."

If it is disallowed, then it is disallowed.

I will not attempt to bypass any restrictions or create cheat software by adding delays or, as some have suggested, implementing functions like "SnapStops." 

I have already addressed this matter in detail [here](https://github.com/cafali/SnapKey/discussions/68). 

Eventually, even your current "fix" is likely to be patched.

**Comment by cafali** [comment]
F
