### ISSUE TITLE
Some pairs of buttons don't work

### ISSUE THREAD

**Issue by ThisIsEXE01** [cafali/SnapKey#79]
I need snapkey to work with Lshift and Lalt, but when I use scancodes 16 and 18, nothing happens. I've experimented a bit with bindings: a + space works, esc + space doesn't work.
I'm using a ‘hyperx alloy fps pro cherry mx red’ keyboard, also I have changed the language change combination: now shift + ctrl.

Sorry if the translation is bad, I'm using a translator.

**Comment by cafali** [comment]
Hi, try this

#ESC SPACE

[Group]
key1=27
key2=32

#Shift Alt
[Group]
key3=160
key5=164

**Comment by ThisIsEXE01** [comment]
Thanks, it works now! Where can I find more special codes?

**Comment by cafali** [comment]
You can find all the key codes and some additional information at the bottom of the page here: [SnapKey Wiki - Rebinding Keys](https://github.com/cafali/SnapKey/wiki/Rebinding-Keys)

**Comment by cafali** [comment]
You can find all relevant keycodes and some additional information at the bottom of the page here: [SnapKey Wiki - Rebinding Keys](https://github.com/cafali/SnapKey/wiki/Rebinding-Keys)
