### ISSUE TITLE
SnapKey interfering with Windows emoji keyboard

### ISSUE THREAD

**Issue by eiqnepm** [cafali/SnapKey#88]
I'm not sure if other people use the Windows emoji keyboard, it's activated using Windows and period, it opens just fine, but when SnapKey is enabled, you're unable to use _SnapKeys_ in the emoji keyboard 💀.

**Comment by cafali** [comment]
Thank you for bringing this up - however, SnapKey is specifically designed for use within games and not for general Windows navigation or applications like the windows emoji keyboard. 

The limitation you mentioned only affects the Arrow Keys, which are typically used for navigation in Windows apps.

An Option to disable SnapKey when not gaming has already been implemented in v.1.2.3/v.1.2.4 to avoid unwanted "Sticky Keys" conflicts with the OS while using it outside of games, so we recommend enabling it only while gaming and turning it off for other tasks outside of games or in situations where SnapKey is not needed.

I’ll be closing this issue as it falls outside the intended scope of the software.

**Comment by eiqnepm** [comment]
> I’ll be closing this issue as it falls outside the intended scope of the software.

Would a toggle hotkey with a different on and off sound be in scope? Being able to enable and disable SnapKey rapidly and with an audible confirmation would definitely be much more convenient than using the tray menu
