### ISSUE TITLE
smartscreen

### ISSUE THREAD

**Issue by ro6axe** [cafali/SnapKey#93]
Hi SnapKey Team,

I've been interested in using SnapKey, but I've encountered a couple of security warnings. SmartScreen flagged it as malicious, and VirusTotal showed one flag. Could you provide any information or assurances regarding these concerns?

Thanks for your help, [ro6axe]

**Comment by kaxlabs** [comment]
Brother, it's open source.

**Comment by cafali** [comment]
> Hi SnapKey Team,
> 
> I've been interested in using SnapKey, but I've encountered a couple of security warnings. SmartScreen flagged it as malicious, and VirusTotal showed one flag. Could you provide any information or assurances regarding these concerns?
> 
> Thanks for your help, [ro6axe]

malware

**Comment by ro6axe** [comment]
Open source can still contain viruses

**Comment by AoElite** [comment]
It's a small project with only a few files, just look at the source code.

**Comment by ro6axe** [comment]
Ok i check it and it was safe thank u

**Comment by ro6axe** [comment]
Thank u all
